-- Enable JSONB support (default in Postgres, just being explicit)

-- 1. COUNTRIES (Módulo 8)
-- Use text ID for country code (e.g., 'MX', 'US')
CREATE TABLE IF NOT EXISTS countries (
    code TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    currency TEXT NOT NULL,
    "phonePrefix" TEXT, -- camelCase quoted to match AppState
    flag TEXT,
    "isActive" BOOLEAN DEFAULT TRUE
);

-- 2. COURSES (Módulo 1)
CREATE TABLE IF NOT EXISTS courses (
    sku TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    benefits TEXT[], -- Array of strings
    instructor TEXT,
    "instructorBio" TEXT,
    duration TEXT,
    modality TEXT,
    "syllabusLink" TEXT,
    "mediaUrl" TEXT,
    status TEXT,
    "sortOrder" INTEGER
);

-- 3. PRICES (Módulo 2)
CREATE TABLE IF NOT EXISTS prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL REFERENCES courses(sku) ON DELETE CASCADE,
    country TEXT NOT NULL REFERENCES countries(code) ON DELETE CASCADE,
    currency TEXT NOT NULL,
    price NUMERIC NOT NULL,
    "promoPrice" NUMERIC,
    "promoStartDate" TEXT, -- ISO Date String
    "promoEndDate" TEXT, -- ISO Date String
    "isActive" BOOLEAN DEFAULT TRUE,
    UNIQUE(sku, country)
);

-- 4. PAYMENT LINKS (Módulo 3)
CREATE TABLE IF NOT EXISTS payment_links (
    id TEXT PRIMARY KEY,
    sku TEXT NOT NULL,
    country TEXT NOT NULL,
    url TEXT NOT NULL,
    "paymentMethods" TEXT[],
    instructions TEXT,
    "isActive" BOOLEAN DEFAULT TRUE
);

-- 5. PROFESSIONS CATALOG (Módulo 4)
CREATE TABLE IF NOT EXISTS professions (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

-- 6. PROFESSION RULES (Módulo 4 Logic)
CREATE TABLE IF NOT EXISTS profession_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku TEXT NOT NULL,
    "professionId" TEXT NOT NULL,
    "isAllowed" BOOLEAN DEFAULT FALSE,
    "requiresCertification" BOOLEAN DEFAULT FALSE,
    notes TEXT,
    UNIQUE(sku, "professionId")
);

-- 7. PIPELINE STAGES (Módulo 5)
CREATE TABLE IF NOT EXISTS pipeline_stages (
    id TEXT PRIMARY KEY,
    "order" INTEGER NOT NULL,
    name TEXT NOT NULL,
    "scriptTemplate" TEXT,
    "requiredInput" TEXT -- Links to contact_properties.key
);

-- 8. CONTACT PROPERTIES (Módulo 9)
CREATE TABLE IF NOT EXISTS contact_properties (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL,
    key TEXT NOT NULL UNIQUE,
    type TEXT NOT NULL,
    description TEXT
);

-- 9. DEALS (Módulo 10, 11, 12)
-- Note: store.tsx maps this table specifically to snake_case, so we use snake_case here.
CREATE TABLE IF NOT EXISTS deals (
    id TEXT PRIMARY KEY,
    customer_name TEXT,
    stage_id TEXT,
    value NUMERIC DEFAULT 0,
    currency TEXT,
    last_interaction TEXT,
    chat_history JSONB DEFAULT '[]'::jsonb,
    captured_data JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 10. FAQS (Módulo 6)
CREATE TABLE IF NOT EXISTS faqs (
    id TEXT PRIMARY KEY,
    question TEXT NOT NULL,
    answer TEXT NOT NULL
);

-- 11. AGENT CONFIG (Módulo 7)
CREATE TABLE IF NOT EXISTS agent_config (
    id INTEGER PRIMARY KEY DEFAULT 1,
    name TEXT,
    tone TEXT,
    model TEXT
);

-- Insert default config if not exists
INSERT INTO agent_config (id, name, tone, model)
VALUES (1, 'VentasBot 3000', 'Friendly', 'gemini-3-flash-preview')
ON CONFLICT (id) DO NOTHING;

-- ROW LEVEL SECURITY (Optional: Open for demo purposes)
ALTER TABLE deals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON deals FOR ALL USING (true) WITH CHECK (true);

-- Repeat for other tables if RLS is strictly required, 
-- but for this demo, we assume the provided anon key has permissions.
